<?php
// $Id$

/**
 * @file
 * Admin_UI module file.
 *
 * This module provides extra UI helpers for Admin module.
 */

/**
 * Implementation of hook_admin_link_alter().
 *
 * To improve inline menu for some nodes types.
 */
function admin_ui_admin_link_alter(&$links, $type, $object) {
  if ($type == 'node') {
    // Inline menu for panel node types
    if ($object->type == 'panel') {
      unset($links['node-edit'], $links['node-delete']);
      if (node_access('update', $object)) {
        $links['node-edit'] = array(
          'title' => t('Configure'),
          'href' => "node/{$object->nid}/edit",
          'attributes' => array('class' => 'icon-configure'),
          'query' => array('destination' => "node/{$object->nid}"),
        );
        $links['node-layout'] = array(
          'title' => t('Layout'),
          'href' => "node/{$object->nid}/panel_layout",
          'attributes' => array('class' => 'icon-configure'),
          'query' => array('destination' => "node/{$object->nid}"),
        );
        $links['node-content'] = array(
          'title' => t('Content'),
          'href' => "node/{$object->nid}/panel_content",
          'attributes' => array('class' => 'icon-edit'),
          'query' => array('destination' => $_GET['q']),
        );
      }
      if (node_access('delete', $object)) {
        $links['node-delete'] = array(
          'title' => t('Delete'),
          'href' => "node/{$object->nid}/delete",
          'attributes' => array('class' => 'icon-delete'),
          'query' => array('destination' => $_GET['q']),
        );
      }
    }
  }

  return $links;
}

/**
 * Implementation of hook_preprocess_page().
 */
function admin_ui_preprocess_page(&$vars) {

	/**
	 * Hid the classic node tabs panel, because we using admin links instead.
	 * TODO: needs review, not sure if it's safe way...
	 */
	if (isset($_GET['q']) && (false !== strpos($_GET['q'], 'node'))) {
		//unset($vars['tabs']);
	}
}

